import type { ObjectOfType } from '@edouardmisset/type'

/**
 * Creates a new object with the same keys as the given object,
 * and values generated by running each own enumerable string keyed property of
 * the object thru the function.
 *
 * @param {Object.<string, Value>} object - The object to iterate over.
 * @param {(value: Value) => Returned} transform - The function invoked per
 * iteration.
 * @returns {Object.<string, Returned>} The new object with the same keys and
 * mapped values.
 *
 * @template Value The type of the values in the input object.
 * @template Returned The type of the values in the returned object.
 *
 * @example
 * ```typescript
 * const object = { a: 1, b: 2 }
 * const fn = (number_: number) => number_ * 2
 * mapObject(object, fn)
 * // returns { a: 2, b: 4 }
 * ```
 */
export function mapObject<
  Object_ extends ObjectOfType<unknown>,
  Value extends Object_[keyof Object_],
  Returned,
  Result extends { [k in keyof Object_]: Returned },
>(
  object: Object_,
  transform: (value: Value) => Returned,
): Result {
  return Object.fromEntries(
    Object.entries(object).map((
      [key, value],
    ) => [key, transform(value as Value)]),
  ) as Result
}
